### ISSUE TITLE
panic: runtime error index out of range [1] with length 1

### ISSUE THREAD

**Issue by Felix2yu** [BoredTape/bilibo#1]
正常运行一段时间后无法启动，这是日志
```
2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:33
[0.057ms] [rows:1] PRAGMA foreign_keys

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:33
[14.797ms] [rows:0] DROP TABLE IF EXISTS `qr_code`

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:33
[9.911ms] [rows:0] DROP TABLE IF EXISTS `task`

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.111ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="bili_accounts"

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.164ms] [rows:2] SELECT sql FROM sqlite_master WHERE type IN ("table","index") AND tbl_name = "bili_accounts" AND sql IS NOT NULL order by type = "table" desc

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.082ms] [rows:-] SELECT * FROM `bili_accounts` LIMIT 1

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.049ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type = "index" AND tbl_name = "bili_accounts" AND name = "idx_bili_accounts_deleted_at"

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.034ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="favour_folders_info"

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.133ms] [rows:2] SELECT sql FROM sqlite_master WHERE type IN ("table","index") AND tbl_name = "favour_folders_info" AND sql IS NOT NULL order by type = "table" desc

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.074ms] [rows:-] SELECT * FROM `favour_folders_info` LIMIT 1

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.050ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type = "index" AND tbl_name = "favour_folders_info" AND name = "idx_favour_folders_info_deleted_at"

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.033ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="videos"

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.135ms] [rows:2] SELECT sql FROM sqlite_master WHERE type IN ("table","index") AND tbl_name = "videos" AND sql IS NOT NULL order by type = "table" desc

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.092ms] [rows:-] SELECT * FROM `videos` LIMIT 1

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.051ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type = "index" AND tbl_name = "videos" AND name = "idx_videos_deleted_at"

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.034ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="videos_info"

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.138ms] [rows:2] SELECT sql FROM sqlite_master WHERE type IN ("table","index") AND tbl_name = "videos_info" AND sql IS NOT NULL order by type = "table" desc

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.089ms] [rows:-] SELECT * FROM `videos_info` LIMIT 1

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.045ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type = "index" AND tbl_name = "videos_info" AND name = "idx_videos_info_deleted_at"

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.033ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="qr_code"

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[8.452ms] [rows:0] CREATE TABLE `qr_code` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`qr_id` text,`status` integer)

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[27.665ms] [rows:0] CREATE INDEX `idx_qr_code_deleted_at` ON `qr_code`(`deleted_at`)

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.277ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="video_download_message"

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.210ms] [rows:2] SELECT sql FROM sqlite_master WHERE type IN ("table","index") AND tbl_name = "video_download_message" AND sql IS NOT NULL order by type = "table" desc

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.048ms] [rows:-] SELECT * FROM `video_download_message` LIMIT 1

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.061ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type = "index" AND tbl_name = "video_download_message" AND name = "idx_video_download_message_deleted_at"

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.036ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="task"

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[27.314ms] [rows:0] CREATE TABLE `task` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`task_id` text,`name` text,`last_running_at` datetime,`next_running_at` datetime,`type` integer)

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[6.675ms] [rows:0] CREATE INDEX `idx_task_deleted_at` ON `task`(`deleted_at`)

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.455ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="watch_later"

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.186ms] [rows:2] SELECT sql FROM sqlite_master WHERE type IN ("table","index") AND tbl_name = "watch_later" AND sql IS NOT NULL order by type = "table" desc

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.047ms] [rows:-] SELECT * FROM `watch_later` LIMIT 1

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.041ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type = "index" AND tbl_name = "watch_later" AND name = "idx_watch_later_deleted_at"

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.034ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="collected_info"

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.189ms] [rows:2] SELECT sql FROM sqlite_master WHERE type IN ("table","index") AND tbl_name = "collected_info" AND sql IS NOT NULL order by type = "table" desc

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.047ms] [rows:-] SELECT * FROM `collected_info` LIMIT 1

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:34
[0.037ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type = "index" AND tbl_name = "collected_info" AND name = "idx_collected_info_deleted_at"

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/models/db.go:45
[80.453ms] [rows:1] UPDATE `videos` SET `status`=0,`updated_at`="2024-07-22 02:05:27.456" WHERE status = 1 AND `videos`.`deleted_at` IS NULL

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/services/account.go:48
[0.490ms] [rows:1] SELECT * FROM `bili_accounts` WHERE `bili_accounts`.`deleted_at` IS NULL

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/services/account.go:55
[0.360ms] [rows:1] SELECT * FROM `bili_accounts` WHERE mid = 64733 AND `bili_accounts`.`deleted_at` IS NULL ORDER BY `bili_accounts`.`id` LIMIT 1

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/services/task.go:49
[1.933ms] [rows:0] SELECT * FROM `task` WHERE task_id = "user_download_64733" AND `task`.`deleted_at` IS NULL ORDER BY `task`.`id` LIMIT 1

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/services/task.go:49
[4.390ms] [rows:0] SELECT * FROM `task` WHERE task_id = "RefreshWbiKey" AND `task`.`deleted_at` IS NULL ORDER BY `task`.`id` LIMIT 1

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/services/task.go:58
[11.557ms] [rows:1] INSERT INTO `task` (`created_at`,`updated_at`,`deleted_at`,`task_id`,`name`,`last_running_at`,`next_running_at`,`type`) VALUES ("2024-07-22 02:05:27.542","2024-07-22 02:05:27.542",NULL,"user_download_64733","用户 [浩曠] 的定时下载","2024-07-22 02:05:27.54",NULL,2) RETURNING `id`
2024-07-22T02:05:27.554Z	INFO	user [64733] download start

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/services/video.go:24
[2.630ms] [rows:1] SELECT * FROM `videos` WHERE (mid = 64733 AND status = 0) AND `videos`.`deleted_at` IS NULL ORDER BY `videos`.`id` LIMIT 1

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/services/task.go:58
[16.908ms] [rows:1] INSERT INTO `task` (`created_at`,`updated_at`,`deleted_at`,`task_id`,`name`,`last_running_at`,`next_running_at`,`type`) VALUES ("2024-07-22 02:05:27.547","2024-07-22 02:05:27.547",NULL,"RefreshWbiKey","更新用户信息","2024-07-22 02:05:27.542",NULL,1) RETURNING `id`
2024-07-22T02:05:27.564Z	INFO	refresh wbi key

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/services/video.go:45
[13.782ms] [rows:1] SELECT * FROM `videos` WHERE (mid = 64733 AND status = 4 AND last_download_at < "2024-07-22 00:05:27.557" AND ((source_id IN (SELECT `mlid` FROM `favour_folders_info` WHERE (`favour_folders_info`.`mid` = 64733 AND `favour_folders_info`.`sync` = 1) AND `favour_folders_info`.`deleted_at` IS NULL) AND type = 1) OR (type = 2)  OR (source_id IN (SELECT `coll_id` FROM `collected_info` WHERE (`collected_info`.`mid` = 64733 AND `collected_info`.`sync` = 1) AND `collected_info`.`deleted_at` IS NULL) AND type = 3))) AND `videos`.`deleted_at` IS NULL ORDER BY `videos`.`id` LIMIT 1

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/services/video.go:397
[13.258ms] [rows:1] SELECT `videos_info`.`bvid`,`videos_info`.`cid`,`videos_info`.`page`,`videos_info`.`title`,`videos_info`.`part`,`videos_info`.`width`,`videos_info`.`height`,`videos_info`.`rotate` FROM `videos_info` WHERE (`videos_info`.`bvid` = "BV1S1421q7fZ" AND `videos_info`.`cid` = 1545113234) AND `videos_info`.`deleted_at` IS NULL ORDER BY `videos_info`.`id` LIMIT 1

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/services/video.go:55
[0.361ms] [rows:1] SELECT * FROM `videos` WHERE id = 22675 AND `videos`.`deleted_at` IS NULL ORDER BY `videos`.`id` LIMIT 1

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/services/video.go:61
[7.619ms] [rows:1] UPDATE `videos` SET `created_at`="2024-07-15 18:21:17.595",`updated_at`="2024-07-22 02:05:27.585",`deleted_at`=NULL,`source_id`=0,`mid`=64733,`bvid`="BV1S1421q7fZ",`cid`=1545113234,`status`=1,`type`=2,`last_download_at`="2024-07-22 02:05:27.585" WHERE `videos`.`deleted_at` IS NULL AND `id` = 22675

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/services/video.go:397
[6.943ms] [rows:1] SELECT `videos_info`.`bvid`,`videos_info`.`cid`,`videos_info`.`page`,`videos_info`.`title`,`videos_info`.`part`,`videos_info`.`width`,`videos_info`.`height`,`videos_info`.`rotate` FROM `videos_info` WHERE (`videos_info`.`bvid` = "BV1S1421q7fZ" AND `videos_info`.`cid` = 1545113234) AND `videos_info`.`deleted_at` IS NULL ORDER BY `videos_info`.`id` LIMIT 1

2024/07/22 02:05:27 /home/runner/work/bilibo/bilibo/services/account.go:11
[0.448ms] [rows:1] SELECT * FROM `bili_accounts` WHERE `bili_accounts`.`mid` = 64733 AND `bili_accounts`.`deleted_at` IS NULL ORDER BY `bili_accounts`.`id` LIMIT 1
panic: runtime error: index out of range [1] with length 1

goroutine 21 [running]:
bilibo/bobo/client.(*Client).DownloadVideoBestByBvidCid(0xc000214000, 0xb?, {0xc0003da490?, 0x4?}, {0xc0003da340, 0xf}, {0xc0000a84a0, 0x1f})
	/home/runner/work/bilibo/bilibo/bobo/client/video.go:776 +0xc5d
bilibo/bobo.downloadHandler(0xc000214000, 0xc0004a0000, {0xc000014990, 0xa}, {0xc000594000, 0x8d})
	/home/runner/work/bilibo/bilibo/bobo/downloader.go:35 +0x23e
bilibo/bobo.downloadVideo(0xc000214000, {0xe84258, 0xc00037ebe0})
	/home/runner/work/bilibo/bilibo/bobo/downloader.go:111 +0x790
created by bilibo/bobo.addClient in goroutine 1
	/home/runner/work/bilibo/bilibo/bobo/bobo.go:76 +0x33f

```

**Comment by BoredTape** [comment]
在处理视频文件后缀名的时候我粗暴切割MimeType取下标1获取的，这里出了问题，方便提供B站投稿的视频地址吗？如果没有的话，我再想想办法。。。

**Comment by Felix2yu** [comment]
我只同步了稍后再看，但是稍后再看里有几百个视频，我无法确定是哪个视频导致的问题。有什么办法能帮助定位具体视频吗

**Comment by BoredTape** [comment]
> 我只同步了稍后再看，但是稍后再看里有几百个视频，我无法确定是哪个视频导致的问题。有什么办法能帮助定位具体视频吗

更新了一版，在panic的地方做了判断，会有"视频Bvid:[xxx],无法获取视频类型:[xxx]"这个日志打印出来。我在过去的几个小时里还没复现出来

**Comment by Felix2yu** [comment]
BV1S1421q7fZ，这是一个充电订阅专属视频，从列表中移除后就正常了。
```
bilibo  | 2024-07-22T16:57:34.285Z      ERROR   视频Bvid:[BV1S1421q7fZ],无法获取视频类型:[mp4]
bilibo  | 2024-07-22T16:57:34.285Z      ERROR   user [64733] get video [BV1S1421q7fZ] info error: 视频Bvid:[BV1S1421q7fZ],无法获取视频类型:[mp4]
```

**Comment by BoredTape** [comment]
> BV1S1421q7fZ，这是一个充电订阅专属视频，从列表中移除后就正常了。
> 
> ```
> bilibo  | 2024-07-22T16:57:34.285Z      ERROR   视频Bvid:[BV1S1421q7fZ],无法获取视频类型:[mp4]
> bilibo  | 2024-07-22T16:57:34.285Z      ERROR   user [64733] get video [BV1S1421q7fZ] info error: 视频Bvid:[BV1S1421q7fZ],无法获取视频类型:[mp4]
> ```

啊，怪我，我没试过在B站充电。。。最新版已经修复充电订阅专属视频获取视频类型的错误，可以试试，因为我没有专属视频测试所以，可能会有问题，如果还有问题的话，我持续跟进。
![啵啵](https://github.com/user-attachments/assets/415c61d7-58d5-4d5f-a639-a3492040f18f)
我家猫说他累了。。。

**Comment by Felix2yu** [comment]
谢谢，一天观察下来没问题了。啵啵挺好看的，辛苦啦 哈哈哈哈
